[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "nft"
  directory = "netlify/functions"

[[redirects]]
  from = "/api/lyrics"
  to = "/.netlify/functions/lyrics"
  status = 200
  force = true